### ISSUE TITLE
Explain how to run these tests in README

### ISSUE THREAD

**Issue by yunho-c** [linebender/resvg-test-suite#50]
Hi, 

I would appreciate the addition of instructions on how to run these tests myself, as `resvg` was not behaving correctly for me and I wasn't sure if it was an issue specific to my local build. 

Thanks!

**Comment by RazrFalcon** [comment]
Those tests are somewhat independent from `resvg`. If you want to test `resvg` itself simply call `cargo test --all` in the root dir of the `resvg` repo.

**Comment by shlyakpavel** [comment]
@RazrFalcon and what about the other projects they compare to? Like chromium etc?
I would like to test https://github.com/LadybirdBrowser/ladybird and add it to comparison

**Comment by RazrFalcon** [comment]
Chromium and Chrome is the same thing. As for ladybird, we explicitly ignore projects that do not reach 25% tests passed mark. Does ladybird capable of that? I don't know. And it will be lot of work to figure that out.

**Comment by shlyakpavel** [comment]
>  And it will be lot of work to figure that out.

Yeah, that exactly what I'm planning to so

**Comment by RazrFalcon** [comment]
Good luck. You would have to patch tools/vdiff, but after that it should be relatively easy, but very time consuming.

**Comment by shlyakpavel** [comment]
@RazrFalcon once I patch vdiff, am I supposed to compare every test against reference with my own eyes, or is there an automated way to do that?

**Comment by RazrFalcon** [comment]
Yep, manually. All ~1600 of them...

**Comment by jwmcglynn** [comment]
I have a wrapper built around resvg-test-suite in my repo that does automatic image comparison. That may be a faster starting point: https://github.com/jwmcglynn/donner/blob/main/donner/svg/renderer/tests/resvg_test_suite.cc

It's using an older version of resvg-test-suite though, before the big rename.  It currently runs a subset, 645 tests, in about 2 minutes.
